[variables]
PYTHON_VERSION = "3.9"

[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "cd backend && python3 -m pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

